"""add invoices table and invoice_id on recovery_cases

Revision ID: 6aafd974aa5b
Revises: bdf9177692b3
Create Date: 2026-09-03 16:18:24.958298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aafd974aa5b'
down_revision: Union[str, None] = 'bdf9177692b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recovery_cases', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.alter_column('recovery_cases', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'recovery_cases', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_cases', type_='foreignkey')
    op.alter_column('recovery_cases', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recovery_cases', 'invoice_id')
    op.drop_table('invoices')
    # ### end Alembic commands ###