"""add care_plans table and plan_id on recovery_cases

Revision ID: d013253fd45f
Revises: 6aafd974aa5b
Create Date: 2026-09-04 14:52:11.203374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd013253fd45f'
down_revision: Union[str, None] = '6aafd974aa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('covers', sa.String(length=300), nullable=False),
    sa.Column('amount_per_cycle', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_interval_days', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recovery_cases', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recovery_cases', 'care_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_cases', type_='foreignkey')
    op.drop_column('recovery_cases', 'plan_id')
    op.drop_table('care_plans')
    # ### end Alembic commands ###