"""
Synthetic merchant catalog for Sellsy AI demo data.

Each product is keyed by a temporary `sku` string so products can reference
each other (compatible_products / upsell_products / cross_sell_products)
before real database IDs exist. seed_catalog.py resolves these sku
references to actual product IDs after insert.

This is demo/seed data only — realistic enough for the AI agent and
recommendation engine to have something meaningful to work with, not real
merchant inventory.
"""

CATALOG = [
    # ---------------- LAPTOPS ----------------
    {
        "sku": "laptop-acer-aspire3",
        "name": "Acer Aspire 3 (Ryzen 5, 8GB/512GB)",
        "description": "Reliable everyday laptop for coursework, browsing, and office apps. Great value for students on a budget.",
        "category": "laptops",
        "price": 42999.00,
        "inventory": 18,
        "features": ["AMD Ryzen 5 7520U", "8GB RAM", "512GB SSD", "15.6\" FHD display", "Windows 11"],
        "tags": ["budget", "student", "everyday-use"],
        "compatible_products": ["mouse-logitech-m221", "backpack-hp-15"],
        "upsell_products": ["mouse-logitech-mx-anywhere3", "monitor-lg-24"],
        "cross_sell_products": ["mouse-logitech-m221", "headset-boat-rockerz"],
    },
    {
        "sku": "laptop-hp-pavilion14",
        "name": "HP Pavilion 14 (i5, 16GB/512GB)",
        "description": "Slim and light mid-range laptop with a sharp display, good for students who also do light creative work.",
        "category": "laptops",
        "price": 58990.00,
        "inventory": 14,
        "features": ["Intel Core i5-1335U", "16GB RAM", "512GB SSD", "14\" 2K display", "Backlit keyboard"],
        "tags": ["mid-range", "student", "portable"],
        "compatible_products": ["mouse-logitech-mx-anywhere3", "backpack-hp-15"],
        "upsell_products": ["monitor-dell-27", "keyboard-logitech-mk270"],
        "cross_sell_products": ["mouse-logitech-mx-anywhere3", "webcam-logitech-c920"],
    },
    {
        "sku": "laptop-lenovo-ideapad-slim5",
        "name": "Lenovo IdeaPad Slim 5 (Ryzen 7, 16GB/512GB)",
        "description": "Well-rounded laptop with strong multitasking performance — handles coding, spreadsheets, and streaming with ease.",
        "category": "laptops",
        "price": 64990.00,
        "inventory": 10,
        "features": ["AMD Ryzen 7 7730U", "16GB RAM", "512GB SSD", "14\" WUXGA display", "Fingerprint reader"],
        "tags": ["mid-range", "coding", "multitasking"],
        "compatible_products": ["mouse-logitech-mx-anywhere3", "monitor-dell-27"],
        "upsell_products": ["monitor-dell-27", "ssd-external-samsung-t7"],
        "cross_sell_products": ["keyboard-keychron-k3", "mouse-logitech-mx-anywhere3"],
    },
    {
        "sku": "laptop-asus-vivobook-s15",
        "name": "ASUS Vivobook S15 (i7, 16GB/1TB)",
        "description": "Powerful all-rounder with a large 1TB SSD — comfortable for heavier workloads like video editing or dev environments.",
        "category": "laptops",
        "price": 74990.00,
        "inventory": 9,
        "features": ["Intel Core i7-13620H", "16GB RAM", "1TB SSD", "15.6\" OLED display", "NVIDIA MX550 graphics"],
        "tags": ["performance", "creative", "large-storage"],
        "compatible_products": ["mouse-logitech-mx-anywhere3", "monitor-dell-27"],
        "upsell_products": ["monitor-lg-ultrawide29", "ssd-external-samsung-t7"],
        "cross_sell_products": ["headset-boat-rockerz", "laptop-stand-rain-design"],
    },
    {
        "sku": "laptop-macbook-air-m2",
        "name": "Apple MacBook Air 13\" (M2, 8GB/256GB)",
        "description": "Thin, silent, and long-lasting — Apple's entry MacBook, ideal for students who want the macOS ecosystem.",
        "category": "laptops",
        "price": 99900.00,
        "inventory": 7,
        "features": ["Apple M2 chip", "8GB unified memory", "256GB SSD", "13.6\" Liquid Retina display", "18-hour battery"],
        "tags": ["premium", "apple", "portable"],
        "compatible_products": ["mouse-logitech-mx-anywhere3", "usb-c-hub-anker"],
        "upsell_products": ["monitor-lg-ultrawide29", "usb-c-hub-anker"],
        "cross_sell_products": ["laptop-stand-rain-design", "usb-c-hub-anker"],
    },
    {
        "sku": "laptop-dell-inspiron15",
        "name": "Dell Inspiron 15 (i3, 8GB/512GB)",
        "description": "No-frills budget laptop that covers the essentials — browsing, documents, and video calls without lag.",
        "category": "laptops",
        "price": 38999.00,
        "inventory": 22,
        "features": ["Intel Core i3-1215U", "8GB RAM", "512GB SSD", "15.6\" FHD display"],
        "tags": ["budget", "entry-level", "student"],
        "compatible_products": ["mouse-logitech-m221", "backpack-hp-15"],
        "upsell_products": ["mouse-logitech-mx-anywhere3", "monitor-lg-24"],
        "cross_sell_products": ["mouse-logitech-m221", "backpack-hp-15"],
    },

    # ---------------- SMARTPHONES ----------------
    {
        "sku": "phone-samsung-galaxy-m34",
        "name": "Samsung Galaxy M34 5G (8GB/128GB)",
        "description": "Solid mid-range 5G phone with a big battery and AMOLED display — great daily driver.",
        "category": "smartphones",
        "price": 17999.00,
        "inventory": 30,
        "features": ["6000mAh battery", "120Hz Super AMOLED", "50MP triple camera", "5G"],
        "tags": ["budget", "5g", "long-battery"],
        "compatible_products": ["earbuds-boat-airdopes", "phone-case-spigen"],
        "upsell_products": ["earbuds-oneplus-buds3", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "screen-protector-generic"],
    },
    {
        "sku": "phone-redmi-note13pro",
        "name": "Redmi Note 13 Pro 5G (8GB/256GB)",
        "description": "Feature-packed mid-ranger with a high-res camera and fast charging, popular with students.",
        "category": "smartphones",
        "price": 24999.00,
        "inventory": 25,
        "features": ["200MP camera", "120W fast charging", "AMOLED display", "5G"],
        "tags": ["mid-range", "camera", "fast-charging"],
        "compatible_products": ["earbuds-oneplus-buds3", "phone-case-spigen"],
        "upsell_products": ["earbuds-sony-wf1000xm4", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "charger-anker-65w"],
    },
    {
        "sku": "phone-oneplus-nord-ce4",
        "name": "OnePlus Nord CE4 (8GB/128GB)",
        "description": "Clean software experience with dependable performance — a favorite for people who want stock-like Android.",
        "category": "smartphones",
        "price": 24999.00,
        "inventory": 20,
        "features": ["Snapdragon 7 Gen 3", "100W SUPERVOOC charging", "OxygenOS", "5G"],
        "tags": ["mid-range", "clean-software", "fast-charging"],
        "compatible_products": ["earbuds-oneplus-buds3", "phone-case-spigen"],
        "upsell_products": ["earbuds-sony-wf1000xm4", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "screen-protector-generic"],
    },
    {
        "sku": "phone-iphone-13",
        "name": "Apple iPhone 13 (128GB)",
        "description": "Still one of Apple's most balanced phones — great cameras, iOS ecosystem, long software support.",
        "category": "smartphones",
        "price": 49900.00,
        "inventory": 12,
        "features": ["A15 Bionic chip", "Dual 12MP camera", "Super Retina XDR display", "5G"],
        "tags": ["premium", "apple", "camera"],
        "compatible_products": ["earbuds-apple-airpods", "phone-case-spigen"],
        "upsell_products": ["earbuds-apple-airpods", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "screen-protector-generic"],
    },
    {
        "sku": "phone-samsung-galaxy-s23fe",
        "name": "Samsung Galaxy S23 FE (8GB/256GB)",
        "description": "Flagship-grade cameras and performance in a more affordable Samsung package.",
        "category": "smartphones",
        "price": 44999.00,
        "inventory": 15,
        "features": ["Snapdragon 8 Gen 1", "50MP OIS camera", "120Hz AMOLED", "IP68 rating"],
        "tags": ["flagship-lite", "camera", "durable"],
        "compatible_products": ["earbuds-sony-wf1000xm4", "phone-case-spigen"],
        "upsell_products": ["earbuds-sony-wf1000xm4", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "charger-anker-65w"],
    },
    {
        "sku": "phone-motorola-g84",
        "name": "Motorola Moto G84 5G (12GB/256GB)",
        "description": "Near-stock Android with a curved pOLED display, punching above its price point.",
        "category": "smartphones",
        "price": 19999.00,
        "inventory": 18,
        "features": ["Snapdragon 695", "pOLED curved display", "50MP OIS camera", "5G"],
        "tags": ["budget", "clean-software", "5g"],
        "compatible_products": ["earbuds-boat-airdopes", "phone-case-spigen"],
        "upsell_products": ["earbuds-oneplus-buds3", "charger-anker-65w"],
        "cross_sell_products": ["phone-case-spigen", "screen-protector-generic"],
    },

    # ---------------- HEADPHONES / EARBUDS ----------------
    {
        "sku": "earbuds-boat-airdopes",
        "name": "boAt Airdopes 141",
        "description": "Budget-friendly true wireless earbuds with long battery backup — a popular starter pair.",
        "category": "headphones",
        "price": 1299.00,
        "inventory": 60,
        "features": ["42h playback", "IPX4 water resistance", "ENx tech for calls"],
        "tags": ["budget", "wireless", "everyday"],
        "compatible_products": ["phone-samsung-galaxy-m34", "phone-motorola-g84"],
        "upsell_products": ["earbuds-oneplus-buds3"],
        "cross_sell_products": ["charger-anker-65w"],
    },
    {
        "sku": "earbuds-oneplus-buds3",
        "name": "OnePlus Buds 3",
        "description": "Well-tuned sound with solid ANC at a mid-range price, pairs seamlessly with OnePlus phones.",
        "category": "headphones",
        "price": 3499.00,
        "inventory": 35,
        "features": ["Active Noise Cancellation", "Dynaudio tuning", "44h total battery"],
        "tags": ["mid-range", "anc", "wireless"],
        "compatible_products": ["phone-oneplus-nord-ce4", "phone-redmi-note13pro"],
        "upsell_products": ["earbuds-sony-wf1000xm4"],
        "cross_sell_products": ["charger-anker-65w"],
    },
    {
        "sku": "earbuds-sony-wf1000xm4",
        "name": "Sony WF-1000XM4",
        "description": "Industry-leading noise cancellation and audio quality — the earbuds upgrade for serious listeners.",
        "category": "headphones",
        "price": 16990.00,
        "inventory": 15,
        "features": ["Best-in-class ANC", "LDAC hi-res audio", "8h battery + case"],
        "tags": ["premium", "anc", "audiophile"],
        "compatible_products": ["phone-iphone-13", "phone-samsung-galaxy-s23fe"],
        "upsell_products": [],
        "cross_sell_products": ["charger-anker-65w"],
    },
    {
        "sku": "earbuds-apple-airpods",
        "name": "Apple AirPods (3rd generation)",
        "description": "Seamless pairing and switching across Apple devices, with spatial audio support.",
        "category": "headphones",
        "price": 17990.00,
        "inventory": 20,
        "features": ["Spatial audio", "MagSafe charging case", "30h total battery"],
        "tags": ["premium", "apple", "wireless"],
        "compatible_products": ["phone-iphone-13", "laptop-macbook-air-m2"],
        "upsell_products": [],
        "cross_sell_products": ["usb-c-hub-anker"],
    },
    {
        "sku": "headset-boat-rockerz",
        "name": "boAt Rockerz 450",
        "description": "Over-ear wireless headphones with punchy bass — good for long study or gaming sessions.",
        "category": "headphones",
        "price": 1499.00,
        "inventory": 40,
        "features": ["15h battery", "40mm dynamic drivers", "Padded ear cushions"],
        "tags": ["budget", "over-ear", "wireless"],
        "compatible_products": ["laptop-acer-aspire3", "laptop-asus-vivobook-s15"],
        "upsell_products": ["earbuds-sony-wf1000xm4"],
        "cross_sell_products": [],
    },
    {
        "sku": "headphones-jbl-tune760nc",
        "name": "JBL Tune 760NC",
        "description": "Comfortable over-ear headphones with active noise cancellation for commutes and study sessions.",
        "category": "headphones",
        "price": 4999.00,
        "inventory": 22,
        "features": ["Active Noise Cancellation", "50h battery", "Foldable design"],
        "tags": ["mid-range", "anc", "over-ear"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-lenovo-ideapad-slim5"],
        "upsell_products": ["earbuds-sony-wf1000xm4"],
        "cross_sell_products": [],
    },

    # ---------------- KEYBOARDS ----------------
    {
        "sku": "keyboard-logitech-mk270",
        "name": "Logitech MK270 Wireless Combo (Keyboard + Mouse)",
        "description": "Reliable wireless keyboard and mouse combo for everyday desk use.",
        "category": "keyboards",
        "price": 1595.00,
        "inventory": 45,
        "features": ["Wireless 2.4GHz", "Spill-resistant", "8 hotkeys", "Includes mouse"],
        "tags": ["budget", "wireless", "combo"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-dell-inspiron15"],
        "upsell_products": ["keyboard-keychron-k3"],
        "cross_sell_products": ["monitor-lg-24"],
    },
    {
        "sku": "keyboard-keychron-k3",
        "name": "Keychron K3 Wireless Mechanical Keyboard",
        "description": "Slim mechanical keyboard with satisfying low-profile switches — popular with developers.",
        "category": "keyboards",
        "price": 6999.00,
        "inventory": 20,
        "features": ["Low-profile mechanical switches", "Bluetooth + wired", "White backlight", "Mac/Windows"],
        "tags": ["mechanical", "developer", "wireless"],
        "compatible_products": ["laptop-lenovo-ideapad-slim5", "laptop-asus-vivobook-s15"],
        "upsell_products": ["keyboard-logitech-mx-mechanical"],
        "cross_sell_products": ["mouse-logitech-mx-anywhere3"],
    },
    {
        "sku": "keyboard-logitech-mx-mechanical",
        "name": "Logitech MX Mechanical",
        "description": "Premium mechanical keyboard with tactile quiet switches, built for long typing sessions.",
        "category": "keyboards",
        "price": 12995.00,
        "inventory": 10,
        "features": ["Tactile quiet switches", "Multi-device Bluetooth", "Backlit keys", "USB-C rechargeable"],
        "tags": ["premium", "mechanical", "multi-device"],
        "compatible_products": ["laptop-macbook-air-m2", "laptop-asus-vivobook-s15"],
        "upsell_products": [],
        "cross_sell_products": ["mouse-logitech-mx-anywhere3"],
    },
    {
        "sku": "keyboard-dell-km3322w",
        "name": "Dell KM3322W Wireless Keyboard & Mouse",
        "description": "Simple, compact wireless combo built for everyday office and study use.",
        "category": "keyboards",
        "price": 1899.00,
        "inventory": 30,
        "features": ["Wireless 2.4GHz", "Compact layout", "Includes mouse", "12-month battery life"],
        "tags": ["budget", "wireless", "combo"],
        "compatible_products": ["laptop-dell-inspiron15", "laptop-acer-aspire3"],
        "upsell_products": ["keyboard-keychron-k3"],
        "cross_sell_products": ["monitor-dell-27"],
    },
    {
        "sku": "keyboard-rapoo-e9700m",
        "name": "Rapoo E9700M Ultra-Slim Wireless Keyboard",
        "description": "Ultra-thin wireless keyboard designed to pair neatly with a laptop setup.",
        "category": "keyboards",
        "price": 2299.00,
        "inventory": 25,
        "features": ["Ultra-slim aluminum body", "Multi-device switching", "Long battery life"],
        "tags": ["slim", "wireless", "multi-device"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-macbook-air-m2"],
        "upsell_products": ["keyboard-logitech-mx-mechanical"],
        "cross_sell_products": ["mouse-logitech-mx-anywhere3"],
    },

    # ---------------- MICE ----------------
    {
        "sku": "mouse-logitech-m221",
        "name": "Logitech M221 Silent Wireless Mouse",
        "description": "Simple, silent-click wireless mouse for everyday use — an easy budget add-on.",
        "category": "mice",
        "price": 799.00,
        "inventory": 80,
        "features": ["Silent clicks", "18-month battery life", "Wireless USB receiver"],
        "tags": ["budget", "wireless", "silent"],
        "compatible_products": ["laptop-acer-aspire3", "laptop-dell-inspiron15"],
        "upsell_products": ["mouse-logitech-mx-anywhere3"],
        "cross_sell_products": [],
    },
    {
        "sku": "mouse-logitech-mx-anywhere3",
        "name": "Logitech MX Anywhere 3",
        "description": "Compact, precise wireless mouse that works on virtually any surface, including glass.",
        "category": "mice",
        "price": 6495.00,
        "inventory": 25,
        "features": ["8000 DPI sensor", "Works on glass", "USB-C fast charging", "Multi-device"],
        "tags": ["premium", "portable", "precision"],
        "compatible_products": ["laptop-macbook-air-m2", "laptop-asus-vivobook-s15"],
        "upsell_products": [],
        "cross_sell_products": ["keyboard-keychron-k3"],
    },
    {
        "sku": "mouse-hp-x1000",
        "name": "HP X1000 Wired Mouse",
        "description": "No-fuss wired mouse — plug and play, ideal as a simple backup or budget pick.",
        "category": "mice",
        "price": 399.00,
        "inventory": 100,
        "features": ["Wired USB", "1200 DPI", "Ambidextrous design"],
        "tags": ["budget", "wired", "entry-level"],
        "compatible_products": ["laptop-dell-inspiron15", "laptop-acer-aspire3"],
        "upsell_products": ["mouse-logitech-m221"],
        "cross_sell_products": [],
    },
    {
        "sku": "mouse-razer-basilisk-v3",
        "name": "Razer Basilisk V3",
        "description": "Ergonomic gaming mouse with customizable RGB and a scroll wheel built for fast-paced games.",
        "category": "mice",
        "price": 5499.00,
        "inventory": 18,
        "features": ["26,000 DPI sensor", "11 programmable buttons", "RGB lighting"],
        "tags": ["gaming", "rgb", "ergonomic"],
        "compatible_products": ["laptop-asus-vivobook-s15", "monitor-lg-ultrawide29"],
        "upsell_products": [],
        "cross_sell_products": ["keyboard-keychron-k3"],
    },
    {
        "sku": "mouse-logitech-signature-m650",
        "name": "Logitech Signature M650",
        "description": "Quiet, comfortable wireless mouse designed for reduced hand strain during long sessions.",
        "category": "mice",
        "price": 2495.00,
        "inventory": 30,
        "features": ["SilentTouch technology", "Customizable buttons", "24-month battery life"],
        "tags": ["ergonomic", "wireless", "quiet"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-lenovo-ideapad-slim5"],
        "upsell_products": ["mouse-logitech-mx-anywhere3"],
        "cross_sell_products": [],
    },

    # ---------------- MONITORS ----------------
    {
        "sku": "monitor-lg-24",
        "name": "LG 24\" FHD IPS Monitor",
        "description": "Affordable second monitor with an IPS panel for good color and viewing angles.",
        "category": "monitors",
        "price": 8999.00,
        "inventory": 20,
        "features": ["24\" Full HD IPS", "75Hz refresh rate", "AMD FreeSync"],
        "tags": ["budget", "second-monitor", "ips"],
        "compatible_products": ["laptop-acer-aspire3", "laptop-dell-inspiron15"],
        "upsell_products": ["monitor-dell-27"],
        "cross_sell_products": ["keyboard-logitech-mk270"],
    },
    {
        "sku": "monitor-dell-27",
        "name": "Dell 27\" QHD Monitor",
        "description": "Sharp QHD monitor that's a strong step up for coding, design, or multitasking with more screen real estate.",
        "category": "monitors",
        "price": 21999.00,
        "inventory": 14,
        "features": ["27\" QHD (2560x1440)", "IPS panel", "USB-C connectivity", "Height adjustable stand"],
        "tags": ["mid-range", "qhd", "productivity"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-lenovo-ideapad-slim5", "laptop-macbook-air-m2"],
        "upsell_products": ["monitor-lg-ultrawide29"],
        "cross_sell_products": ["keyboard-keychron-k3", "mouse-logitech-mx-anywhere3"],
    },
    {
        "sku": "monitor-lg-ultrawide29",
        "name": "LG 29\" UltraWide Monitor",
        "description": "Ultrawide display that gives serious multitasking room — great for split-screen work and creative editing.",
        "category": "monitors",
        "price": 26999.00,
        "inventory": 8,
        "features": ["29\" UltraWide FHD (2560x1080)", "IPS panel", "AMD FreeSync", "Dual HDMI"],
        "tags": ["premium", "ultrawide", "multitasking"],
        "compatible_products": ["laptop-asus-vivobook-s15", "laptop-macbook-air-m2"],
        "upsell_products": [],
        "cross_sell_products": ["mouse-razer-basilisk-v3"],
    },
    {
        "sku": "monitor-samsung-24-curved",
        "name": "Samsung 24\" Curved Monitor",
        "description": "Curved panel that adds a bit of immersion to everyday work and media without a big price jump.",
        "category": "monitors",
        "price": 11999.00,
        "inventory": 16,
        "features": ["24\" curved VA panel", "75Hz refresh rate", "Eye Saver Mode"],
        "tags": ["mid-range", "curved", "second-monitor"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-lenovo-ideapad-slim5"],
        "upsell_products": ["monitor-dell-27"],
        "cross_sell_products": ["keyboard-logitech-mk270"],
    },
    {
        "sku": "monitor-benq-gw2480",
        "name": "BenQ GW2480 24\" Eye-Care Monitor",
        "description": "Low blue-light monitor designed for comfortable long study or work sessions.",
        "category": "monitors",
        "price": 9499.00,
        "inventory": 18,
        "features": ["23.8\" FHD IPS", "Brightness Intelligence", "Flicker-free technology"],
        "tags": ["budget", "eye-care", "second-monitor"],
        "compatible_products": ["laptop-acer-aspire3", "laptop-dell-inspiron15"],
        "upsell_products": ["monitor-dell-27"],
        "cross_sell_products": ["keyboard-logitech-mk270"],
    },

    # ---------------- ACCESSORIES ----------------
    {
        "sku": "backpack-hp-15",
        "name": "HP 15.6\" Laptop Backpack",
        "description": "Padded, water-resistant backpack sized for 15.6\" laptops — a natural add-on for any new laptop purchase.",
        "category": "accessories",
        "price": 1499.00,
        "inventory": 50,
        "features": ["Padded laptop compartment", "Water-resistant fabric", "Multiple pockets"],
        "tags": ["budget", "student", "laptop-bag"],
        "compatible_products": ["laptop-acer-aspire3", "laptop-hp-pavilion14", "laptop-dell-inspiron15"],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "usb-c-hub-anker",
        "name": "Anker 6-in-1 USB-C Hub",
        "description": "Adds HDMI, USB-A, and card reader ports to slim laptops with limited connectivity.",
        "category": "accessories",
        "price": 2999.00,
        "inventory": 35,
        "features": ["4K HDMI output", "2x USB-A 3.0", "SD/microSD card reader", "100W USB-C passthrough charging"],
        "tags": ["connectivity", "portable", "essential"],
        "compatible_products": ["laptop-macbook-air-m2", "laptop-asus-vivobook-s15"],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "ssd-external-samsung-t7",
        "name": "Samsung T7 1TB Portable SSD",
        "description": "Fast, pocket-sized external storage for backups, project files, or media libraries.",
        "category": "accessories",
        "price": 8499.00,
        "inventory": 22,
        "features": ["1TB capacity", "Up to 1050MB/s read speed", "USB 3.2 Gen 2", "Shock-resistant"],
        "tags": ["storage", "portable", "fast"],
        "compatible_products": ["laptop-asus-vivobook-s15", "laptop-lenovo-ideapad-slim5"],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "webcam-logitech-c920",
        "name": "Logitech C920 HD Webcam",
        "description": "Reliable 1080p webcam for video calls and online classes — a common add-on for slimmer laptops.",
        "category": "accessories",
        "price": 5999.00,
        "inventory": 20,
        "features": ["1080p/30fps video", "Stereo audio with dual mics", "Auto light correction"],
        "tags": ["video-calls", "webcam", "student"],
        "compatible_products": ["laptop-hp-pavilion14", "laptop-lenovo-ideapad-slim5"],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "laptop-stand-rain-design",
        "name": "Rain Design mStand Laptop Stand",
        "description": "Aluminum laptop stand that raises the screen to eye level and improves airflow.",
        "category": "accessories",
        "price": 3499.00,
        "inventory": 25,
        "features": ["Aluminum unibody", "Improves posture", "Passive cooling design"],
        "tags": ["ergonomic", "desk-setup"],
        "compatible_products": ["laptop-macbook-air-m2", "laptop-asus-vivobook-s15"],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "phone-case-spigen",
        "name": "Spigen Rugged Armor Phone Case",
        "description": "Shock-absorbing, slim-fit phone case — a near-automatic add-on for any new phone purchase.",
        "category": "accessories",
        "price": 899.00,
        "inventory": 90,
        "features": ["Shock-absorbing corners", "Slim profile", "Raised bezel for screen protection"],
        "tags": ["budget", "protection", "phone-accessory"],
        "compatible_products": [
            "phone-samsung-galaxy-m34",
            "phone-redmi-note13pro",
            "phone-oneplus-nord-ce4",
            "phone-iphone-13",
        ],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "screen-protector-generic",
        "name": "Tempered Glass Screen Protector",
        "description": "Scratch-resistant tempered glass protector, a low-cost add-on for any smartphone.",
        "category": "accessories",
        "price": 399.00,
        "inventory": 120,
        "features": ["9H hardness tempered glass", "Anti-fingerprint coating", "Bubble-free installation"],
        "tags": ["budget", "protection", "phone-accessory"],
        "compatible_products": [
            "phone-samsung-galaxy-m34",
            "phone-redmi-note13pro",
            "phone-motorola-g84",
        ],
        "upsell_products": [],
        "cross_sell_products": [],
    },
    {
        "sku": "charger-anker-65w",
        "name": "Anker 65W GaN Fast Charger",
        "description": "Compact fast charger that can power a laptop, phone, or tablet from a single small brick.",
        "category": "accessories",
        "price": 2499.00,
        "inventory": 40,
        "features": ["65W USB-C output", "GaN technology", "Compact size", "Multi-device compatible"],
        "tags": ["charging", "fast-charging", "essential"],
        "compatible_products": [
            "phone-samsung-galaxy-m34",
            "phone-redmi-note13pro",
            "phone-oneplus-nord-ce4",
            "laptop-macbook-air-m2",
        ],
        "upsell_products": [],
        "cross_sell_products": [],
    },
]
